service: cart-service
frameworkVersion: '3'
useDotenv: true

provider:
    name: aws
    runtime: nodejs16.x
    stage: dev
    region: eu-west-1

    environment:
        PG_HOST: ${env:PG_HOST}
        PG_NAME: ${env:PG_NAME}
        PG_USERNAME: ${env:PG_USERNAME}
        PG_PASSWORD: ${env:PG_PASSWORD}

functions:
    rdsIntegration:
        handler: src/handlers/rdsIntegration.handler